(() => {
  const B=Brasa, $=s=>document.querySelector(s), E=B.escape, M=B.money, I=B.icon;
  const state={cart:B.validateCart(B.get('brasa-cart',[])),coupon:B.get('brasa-coupon',''),category:'destaques',query:'',mode:B.get('brasa-delivery',{mode:'delivery',neighborhood:''}).mode||'delivery',neighborhood:B.get('brasa-delivery',{neighborhood:''}).neighborhood||'',step:0,authMethod:'password',codeSent:false,customer:{name:'',phone:'',email:'',street:'',number:'',complement:'',payment:'Pix',change:'',timing:'now',schedule:''},tracking:null};
  let productDraft=null;
  const count=()=>state.cart.reduce((s,i)=>s+i.qty,0);
  const currentTotals=()=>B.totals(state.cart,state.coupon,state.mode,state.neighborhood);
  const closeButton=()=>`<button class="icon-button" data-action="close" aria-label="Fechar">${I('close')}</button>`;
  const show=id=>{const dialog=$(id);if(!dialog.open)dialog.showModal();return dialog};
  function persist(){B.save('brasa-cart',state.cart);B.save('brasa-coupon',state.coupon);B.save('brasa-delivery',{mode:state.mode,neighborhood:state.neighborhood});updateCartBadges()}
  function updateCartBadges(){document.querySelectorAll('.cart-count').forEach(el=>el.textContent=count());$('.mobile-cart').hidden=!count();$('#mobile-total').textContent=M(currentTotals().total);$('.cart-button').setAttribute('aria-label',`Abrir carrinho, ${count()} itens`)}
  function storeStatus(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Sao_Paulo',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());const values=Object.fromEntries(parts.map(p=>[p.type,p.value]));const time=Number(values.hour)*60+Number(values.minute);const open=values.weekday!=='Mon'&&time>=1080&&time<1410;$('#store-status').textContent=open?'Aberto até 23h30':'Fechado · ter–dom, 18h';if(values.weekday==='Mon')$('#store-status').textContent='Fechado · abre terça às 18h';$('.store-status').style.color=open?'':'var(--muted)'}
  function renderMenu(){
    $('#categories').innerHTML=B.categories.map(c=>`<button class="category ${state.category===c.id?'selected':''}" aria-pressed="${state.category===c.id}" data-category="${c.id}">${I(c.icon)}${c.name}</button>`).join('');
    const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
    const list=B.products.filter(p=>(state.category==='todos'||state.category==='destaques'&&p.featured||p.category===state.category)&&normalize(p.name+' '+p.description).includes(normalize(state.query)));
    const category=B.categories.find(c=>c.id===state.category);$('#menu-title').innerHTML=`${I(category.icon)} ${state.query?'Resultados da busca':state.category==='destaques'?'Os favoritos da casa':category.name}`;$('#product-count').textContent=`${list.length} opções na brasa`;
    $('#product-grid').innerHTML=list.map(p=>`<article class="product-card"><button class="product-image-button" data-product="${p.id}" aria-label="Personalizar ${E(p.name)}"><img src="assets/${p.id}.png" alt="${E(p.name)}" loading="lazy" width="1536" height="1024">${p.badge?`<span class="product-badge">${I('flame')}${E(p.badge)}</span>`:''}</button><div class="product-body"><h3><button data-product="${p.id}" style="padding:0;text-align:left;font:inherit">${E(p.name)}</button></h3><p>${E(p.description)}</p><div class="product-bottom"><span class="product-price"><small>${p.custom?'a partir de':'por'}</small>${M(p.price)}</span><button class="add-button" data-product="${p.id}" aria-label="Adicionar ${E(p.name)}">${I('plus')}</button></div></div></article>`).join('');$('#empty-search').hidden=!!list.length;
  }
  function openProduct(id){const p=B.products.find(p=>p.id===id);if(!p)return;productDraft={productId:id,qty:1,extras:[],removed:[],note:''};const dialog=$('#product-dialog');dialog.innerHTML=`${closeButton()}<div class="product-detail-layout"><div class="product-detail-photo"><img src="assets/${p.id}.png" alt="${E(p.name)}"></div><div class="product-detail-content"><p class="eyebrow">FEITO NA HORA, DO SEU JEITO</p><h2 id="product-title">${E(p.name)}</h2><p class="description">${E(p.description)}</p><p class="price">${M(p.price)}</p>${p.custom?`<section class="option-group"><div class="option-heading"><h3>Uma dose extra de sabor</h3><span>Opcional · até 3</span></div>${B.extras.map(e=>`<label class="check-option"><input type="checkbox" name="extra" value="${e.id}"><span>${E(e.name)}</span><span class="extra-price">+ ${M(e.price)}</span></label>`).join('')}</section>`:''}${p.ingredients.length?`<section class="option-group"><div class="option-heading"><h3>Prefere sem algum ingrediente?</h3><span>Opcional</span></div>${p.ingredients.map(i=>`<label class="check-option"><input type="checkbox" name="remove" value="${E(i)}">Sem ${E(i.toLowerCase())}</label>`).join('')}</section>`:''}<section class="option-group"><label class="field"><span>Algum pedido especial?</span><textarea id="product-note" maxlength="240" placeholder="Ex.: cortar o burger ao meio."></textarea><small>Até 240 caracteres. Alergias? Fale com a equipe.</small></label></section></div></div><div class="product-footer"><div class="stepper"><button data-action="product-minus" aria-label="Diminuir quantidade">−</button><span id="product-qty">1</span><button data-action="product-plus" aria-label="Aumentar quantidade">+</button></div><button class="button primary" data-action="add-product">Adicionar <strong id="product-total">${M(p.price)}</strong></button></div>`;dialog.setAttribute('aria-labelledby','product-title');show('#product-dialog');updateProductPrice()}
  function updateProductPrice(){if(!productDraft)return;$('#product-qty').textContent=productDraft.qty;$('#product-total').textContent=M(B.unit(productDraft)*productDraft.qty);$('[data-action="product-minus"]').disabled=productDraft.qty===1;$('[data-action="product-plus"]').disabled=productDraft.qty===20}
  function addProduct(){productDraft.note=$('#product-note').value.trim();state.cart.push({...productDraft,key:Date.now().toString(36)+Math.random().toString(36).slice(2,6)});persist();$('#product-dialog').close();B.toast(`${B.products.find(p=>p.id===productDraft.productId).name} no carrinho. Boa escolha!`)}
  function totalsMarkup(t,deliveryLabel){return `<div class="totals"><div><span>Subtotal</span><span>${M(t.subtotal)}</span></div>${t.discount?`<div class="discount"><span>BRASA15 · 15% OFF</span><span>− ${M(t.discount)}</span></div>`:''}<div><span>${deliveryLabel||'Entrega'}</span><span>${t.fee===null?'A definir':t.fee===0?'Grátis':M(t.fee)}</span></div><div class="total"><span>${t.fee===null?'Total parcial':'Total'}</span><strong>${M(t.total)}</strong></div></div>`}
  function renderCart(){const d=$('#cart-dialog');d.innerHTML=`<div class="dialog-head"><h2 id="cart-title">Sua próxima brasa <small style="color:var(--orange)">(${count()})</small></h2>${closeButton()}</div>${state.cart.length?`<div class="dialog-body">${state.cart.map((item,index)=>{const p=B.products.find(p=>p.id===item.productId);return `<article class="cart-item"><img src="assets/${p.id}.png" alt="${E(p.name)}"><div><div class="cart-item-heading"><h3>${E(p.name)}</h3><button class="remove-item" data-remove="${index}" aria-label="Remover ${E(p.name)}">${I('trash')}</button></div><p>${item.extras.length?'Com '+item.extras.map(id=>E(B.extras.find(e=>e.id===id).name)).join(', ')+'. ':''}${item.removed.length?'Sem '+item.removed.map(E).join(', ')+'. ':''}${E(item.note)||(!item.extras.length&&!item.removed.length?'Feito na brasa, na hora.':'')}</p><div class="cart-item-bottom"><div class="stepper"><button data-quantity="${index}" data-delta="-1" aria-label="Diminuir ${E(p.name)}">−</button><span>${item.qty}</span><button data-quantity="${index}" data-delta="1" aria-label="Aumentar ${E(p.name)}" ${item.qty>=20?'disabled':''}>+</button></div><strong>${M(B.unit(item)*item.qty)}</strong></div></div></article>`}).join('')}<label class="field"><span>${I('pin')} Onde a brasa vai chegar?</span><select id="cart-neighborhood"><option value="">Selecione seu bairro</option>${Object.keys(B.fees).map(n=>`<option ${state.mode==='delivery'&&state.neighborhood===n?'selected':''}>${E(n)}</option>`).join('')}<option value="pickup" ${state.mode==='pickup'?'selected':''}>Vou retirar · grátis</option></select></label><form id="coupon-form"><label class="field" for="coupon-input">Tem um cupom?</label><div class="coupon-form"><input class="text-input" id="coupon-input" value="${E(state.coupon)}" placeholder="Digite seu cupom" maxlength="20" aria-label="Cupom de desconto"><button class="button secondary" type="submit">Aplicar</button></div><p class="coupon-feedback" id="coupon-feedback">${state.coupon==='BRASA15'?'Cupom aplicado. Seu pedido ganhou 15% OFF.':''}</p>${state.coupon?'<button class="text-link" type="button" data-action="remove-coupon" style="font-size:11px;margin-top:5px">Remover cupom</button>':''}</form></div><div class="drawer-summary">${totalsMarkup(currentTotals(),state.mode==='pickup'?'Retirada':'Taxa de entrega')}<button class="button primary full" data-action="checkout">Continuar para o pedido ${I('arrow')}</button><p class="small-note">Pedido de demonstração · Pagamento somente na entrega ou retirada</p></div>`:`<div class="dialog-body empty-state">${I('bag')}<h3>Está faltando brasa aqui.</h3><p>Escolha seu burger favorito e a gente<br>cuida da sua fome.</p><button class="button primary" data-action="browse">Explorar o cardápio ${I('arrow')}</button></div>`}`;d.setAttribute('aria-labelledby','cart-title')}
  function openCart(){renderCart();show('#cart-dialog')}
  function startCheckout(){if(!state.cart.length)return;$('#cart-dialog').close();state.step=0;renderCheckout();show('#checkout-dialog')}
  const field=(name,label,type='text',required=true,extra='')=>`<label class="field"><span>${label}</span><input name="${name}" type="${type}" value="${E(state.customer[name])}" ${required?'required':''} ${extra}></label>`;
  function checkoutContent(){const c=state.customer;
    if(state.step===0)return `<h2 class="checkout-title">Primeiro, vamos nos conhecer.</h2><p class="checkout-intro">Sua identificação faz parte do pedido. Use dados fictícios para experimentar.</p><button type="button" class="button secondary full" data-action="demo-data">Preencher com dados de demonstração</button><div style="height:20px"></div>${field('name','Seu nome','text',true,'autocomplete="name" minlength="2" maxlength="70"')}${field('phone','WhatsApp com DDD','tel',true,'placeholder="(11) 99999-2026" autocomplete="tel" maxlength="16" pattern="[0-9 ()+\\-]{10,16}"')}${field('email','E-mail','email',true,'autocomplete="email" maxlength="100"')}<div class="form-tabs" aria-label="Forma de identificação"><button type="button" data-auth="password" class="${state.authMethod==='password'?'selected':''}">${I('lock')} Com senha</button><button type="button" data-auth="code" class="${state.authMethod==='code'?'selected':''}">Com código</button></div>${state.authMethod==='password'?`<label class="field"><span>Senha demonstrativa</span><input type="password" name="demoPassword" required minlength="4" value="brasa-demo" autocomplete="off"><small>Login simulado. Use “brasa-demo”; nenhuma senha será salva.</small></label>`:`<label class="field"><span>Receber código por</span><select name="codeChannel"><option>E-mail</option><option>WhatsApp</option></select></label><button type="button" class="button secondary full" data-action="send-code">${state.codeSent?'Gerar outro código de demonstração':'Simular envio do código'}</button>${state.codeSent?'<label class="field" style="margin-top:16px"><span>Código de demonstração: 123456</span><input name="demoCode" inputmode="numeric" pattern="123456" maxlength="6" required placeholder="123456"><small>Nenhuma mensagem foi enviada.</small></label>':''}`}`;
    if(state.step===1)return `<h2 class="checkout-title">Como sua brasa vai chegar?</h2><p class="checkout-intro">Entrega em 35–50 min. Retirada estimada em 25–35 min.</p><div class="choice-grid"><label class="choice-card"><input type="radio" name="mode" value="delivery" ${state.mode==='delivery'?'checked':''}>${I('truck')}<span>Delivery<small>A partir de R$ 5,90</small></span></label><label class="choice-card"><input type="radio" name="mode" value="pickup" ${state.mode==='pickup'?'checked':''}>${I('bag')}<span>Vou retirar<small>Grátis</small></span></label></div>${state.mode==='delivery'?`<label class="field"><span>Bairro</span><select name="neighborhood" required><option value="">Selecione seu bairro</option>${Object.entries(B.fees).map(([n,v])=>`<option value="${E(n)}" ${state.neighborhood===n?'selected':''}>${E(n)} · ${M(v)}</option>`).join('')}</select></label>${field('street','Rua ou avenida','text',true,'maxlength="120"')}<div class="field-row">${field('number','Número','text',true,'maxlength="12"')}${field('complement','Complemento (opcional)','text',false,'maxlength="70"')}</div>`:`<div class="info-box"><strong>${I('pin')} Rua das Brasas, 147 — Centro</strong><p>Apresente o número do pedido no balcão. Retirada gratuita.</p></div>`}<label class="field"><span>Quando você quer seu pedido?</span><select name="timing"><option value="now" ${c.timing==='now'?'selected':''}>O quanto antes · simulação</option><option value="scheduled" ${c.timing==='scheduled'?'selected':''}>Agendar para outro horário</option></select></label>${c.timing==='scheduled'?field('schedule','Data e horário · Brasília','datetime-local',true):''}<p class="muted">Terça a domingo, das 18h às 23h30. Agendamentos seguem esse horário.</p>`;
    if(state.step===2)return `<h2 class="checkout-title">Tudo certo. Como vai pagar?</h2><p class="checkout-intro">Pagamento na ${state.mode==='pickup'?'retirada':'entrega'}. Você não será cobrado agora.</p><div class="choice-grid">${[['Pix','pix'],['Dinheiro','money'],['Débito','card'],['Crédito','card']].map(([p,icon])=>`<label class="choice-card"><input type="radio" name="payment" value="${p}" ${c.payment===p?'checked':''}>${I(icon)}<span>${p}</span></label>`).join('')}</div>${c.payment==='Dinheiro'?field('change','Troco para quanto? (opcional)','number',false,'min="0" step="0.01" placeholder="Ex.: 100,00"'):`<div class="info-box"><strong>${c.payment==='Pix'?'Pix na hora de receber':'Maquininha com a equipe'}</strong><p>${c.payment==='Pix'?'Solicite os dados para pagamento à equipe quando receber o pedido.':'Tenha seu cartão em mãos na hora de receber ou retirar o pedido.'}</p></div>`}<div class="info-box"><strong>Seu pedido até aqui</strong>${totalsMarkup(currentTotals(),state.mode==='pickup'?'Retirada':'Entrega')}</div>`;
    return `<h2 class="checkout-title">Só falta dar o sinal pra brasa.</h2><p class="checkout-intro">Confira os detalhes antes de concluir seu pedido de demonstração.</p><section class="review-section"><button class="edit" type="button" data-step="0">Editar</button><h3>${I('user')} Seus dados</h3><p>${E(c.name)} · ${E(c.phone)}<br>${E(c.email)}</p></section><section class="review-section"><button class="edit" type="button" data-step="1">Editar</button><h3>${I(state.mode==='pickup'?'bag':'pin')} ${state.mode==='pickup'?'Retirada no balcão':'Entrega'}</h3><p>${state.mode==='pickup'?'Rua das Brasas, 147 — Centro':`${E(c.street)}, ${E(c.number)}${c.complement?' · '+E(c.complement):''}<br>${E(state.neighborhood)}`}${c.timing==='scheduled'?`<br>Agendado: ${formatSchedule(c.schedule)}`:''}</p></section><section class="review-section"><button class="edit" type="button" data-step="2">Editar</button><h3>${I('card')} ${E(c.payment)} na ${state.mode==='pickup'?'retirada':'entrega'}</h3>${c.payment==='Dinheiro'&&c.change?`<p>Troco para ${M(Math.round(Number(c.change)*100))}</p>`:''}</section><div class="review-products">${state.cart.map(item=>`<div><span>${item.qty}× ${E(B.products.find(p=>p.id===item.productId).name)}${item.extras.length?`<small class="muted" style="display:block">+ ${item.extras.map(id=>E(B.extras.find(e=>e.id===id).name)).join(', ')}</small>`:''}${item.removed.length?`<small class="muted" style="display:block">Sem ${item.removed.map(E).join(', ')}</small>`:''}${item.note?`<small class="muted" style="display:block">${E(item.note)}</small>`:''}</span><strong>${M(B.unit(item)*item.qty)}</strong></div>`).join('')}</div>${totalsMarkup(currentTotals(),state.mode==='pickup'?'Retirada':'Entrega')}<label class="check-option"><input type="checkbox" name="demoAgreement" required>Entendi que este é um pedido de demonstração, sem envio ou cobrança.</label>`;
  }
  function formatSchedule(s){return s?E(s.split('T')[0].split('-').reverse().join('/')+' às '+s.split('T')[1]):''}
  function renderCheckout(){const names=['Seus dados','Entrega','Pagamento','Revisão'];$('#checkout-dialog').innerHTML=`<div class="dialog-head"><h2 id="checkout-title">Seu pedido, do seu jeito.</h2>${closeButton()}</div><div class="checkout-steps">${names.map((name,i)=>`<div class="checkout-step ${i===state.step?'active':i<state.step?'done':''}" ${i===state.step?'aria-current="step"':''}><b>${i<state.step?'✓':i+1}</b>${name}</div>`).join('')}</div><form id="checkout-form" class="dialog-body">${checkoutContent()}<p class="error-message" id="checkout-error" role="alert"></p><div class="checkout-actions"><button type="button" class="button secondary" data-action="checkout-back">${state.step?'Voltar':'Voltar ao carrinho'}</button><button class="button primary" type="submit">${state.step===3?'Confirmar pedido simulado':'Continuar'} ${I('arrow')}</button></div></form>`;$('#checkout-dialog').setAttribute('aria-labelledby','checkout-title');$('#checkout-dialog').scrollTop=0}
  function captureCheckout(){const f=$('#checkout-form');if(!f)return;const data=new FormData(f);for(const key of Object.keys(state.customer))if(data.has(key))state.customer[key]=String(data.get(key)).trim();if(data.has('neighborhood'))state.neighborhood=data.get('neighborhood');if(data.has('mode'))state.mode=data.get('mode');persist()}
  function validateStep(){const c=state.customer;if(state.step===0){const digits=c.phone.replace(/\D/g,'');if(![10,11].includes(digits.length))return 'Informe um WhatsApp com DDD e 10 ou 11 dígitos.';if(state.authMethod==='code'&&!state.codeSent)return 'Simule o envio do código para continuar.';if(state.authMethod==='code'&&new FormData($('#checkout-form')).get('demoCode')!=='123456')return 'Use o código demonstrativo 123456.'}if(state.step===1){if(state.mode==='delivery'&&!B.fees[state.neighborhood])return 'Selecione um dos bairros atendidos.';if(c.timing==='scheduled'){const d=new Date(c.schedule);const nowParts=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date()).replace(' ','T');const time=d.getHours()*60+d.getMinutes();if(!Number.isFinite(d.getTime())||c.schedule<=nowParts)return 'Escolha uma data e um horário futuros.';if(d.getDay()===1||time<1080||time>1410)return 'Agende de terça a domingo, entre 18h e 23h30, no horário de Brasília.'}}if(state.step===2&&c.payment==='Dinheiro'&&c.change&&Math.round(Number(c.change)*100)<currentTotals().total)return 'O valor para troco precisa ser igual ou maior que o total.';return ''}
  function confirmOrder(){const orders=B.get('brasa-orders',[]);const seq=Math.max(2026,...orders.map(o=>Number(o.number)||2026))+1;const order={number:String(seq),created:new Date().toISOString(),cart:structuredClone(state.cart),totals:currentTotals(),coupon:state.coupon,mode:state.mode,neighborhood:state.neighborhood,customer:{...state.customer},status:'Recebido',demo:true};orders.unshift(order);if(!B.save('brasa-orders',orders)){B.toast('Não foi possível salvar o pedido no navegador. Tente liberar espaço.');return}B.save('brasa-last-order',order.number);state.tracking=order;state.cart=[];state.coupon='';persist();$('#checkout-dialog').innerHTML=`<div class="dialog-head"><h2>Pedido de demonstração</h2>${closeButton()}</div><div class="dialog-body"><div class="confirmation"><div class="confirmation-icon">${I('check')}</div><p class="eyebrow" style="justify-content:center">DEU MATCH COM A BRASA.</p><h2>SEU PEDIDO ESTÁ NA ÁREA!</h2><p>Obrigado, ${E(order.customer.name.split(' ')[0])}.<br>Esta foi uma simulação. Nenhum pedido foi enviado.</p><div class="order-number">#${order.number}</div><p>${order.customer.timing==='scheduled'?'Agendado para '+formatSchedule(order.customer.schedule):`Previsão simulada: ${order.mode==='pickup'?'25–35':'35–50'} minutos`}</p></div><div class="info-box"><strong>${E(order.customer.payment)} na ${order.mode==='pickup'?'retirada':'entrega'} · ${M(order.totals.total)}</strong><p>${order.mode==='pickup'?'Rua das Brasas, 147 — Centro':E(order.customer.street)+', '+E(order.customer.number)+' — '+E(order.neighborhood)}</p></div><button class="button primary full" data-action="track-current">Acompanhar pedido ${I('arrow')}</button><button class="button secondary full" style="margin-top:10px" data-action="close">Voltar ao cardápio</button></div>`}
  function trackingLookup(){const latest=B.get('brasa-last-order','');$('#tracking-dialog').innerHTML=`<div class="dialog-head"><h2 id="tracking-title">Cadê minha brasa?</h2>${closeButton()}</div><form id="tracking-form" class="dialog-body"><p class="checkout-intro">Consulte um pedido simulado com o número e o WhatsApp informado na compra.</p><label class="field"><span>Número do pedido</span><input class="text-input" name="order" placeholder="Ex.: 2027" value="${E(latest)}" required inputmode="numeric" maxlength="12"></label><label class="field"><span>WhatsApp com DDD</span><input class="text-input" name="phone" placeholder="(11) 99999-2026" required type="tel" maxlength="16"></label><p id="tracking-error" class="error-message" role="alert"></p><button class="button primary full">Encontrar meu pedido ${I('search')}</button>${latest?'<button class="text-link" type="button" data-action="last-order">Ver meu último pedido neste navegador</button>':''}<div class="demo-controls"><p>Ainda não fez um pedido? Explore um exemplo.</p><button class="button secondary full" type="button" data-action="sample-order">Abrir acompanhamento de demonstração</button></div></form>`;$('#tracking-dialog').setAttribute('aria-labelledby','tracking-title');show('#tracking-dialog')}
  function sampleOrder(){state.tracking={number:'2026',created:new Date().toISOString(),customer:{name:'Cliente demonstração',phone:'(11) 99999-2026',payment:'Pix',street:'Rua Exemplo',number:'123',timing:'now'},mode:'delivery',neighborhood:'Centro',totals:{total:3996},status:'Em preparação',sample:true};renderTracking()}
  function renderTracking(){const o=state.tracking;if(!o)return;const statusIndex=B.statuses.indexOf(o.status);const canceled=statusIndex>=5;const sequence=['Recebido','Confirmado','Em preparação',o.mode==='pickup'?'Pronto para retirada':'Saiu para entrega',o.mode==='pickup'?'Retirado':'Entregue'];$('#tracking-dialog').innerHTML=`<div class="dialog-head"><h2 id="tracking-title">Pedido #${E(o.number)}</h2>${closeButton()}</div><div class="dialog-body"><p class="eyebrow">${o.sample?'EXEMPLO DE ACOMPANHAMENTO':'ACOMPANHAMENTO SIMULADO'}</p><h2 class="checkout-title">${canceled?(o.status==='Cancelado'?'Pedido cancelado.':'Pedido recusado.'):statusIndex===4?'Brasa entregue. Bom apetite!':statusIndex===3?(o.mode==='pickup'?'Sua brasa está pronta!':'A brasa está a caminho!'):'Sua próxima mordida está chegando.'}</h2><p class="checkout-intro">${canceled?'Este estado foi simulado. Nenhuma cobrança foi realizada.':E(o.customer.name.split(' ')[0])+', acompanhe cada etapa por aqui.'}</p><div class="tracking-summary"><div>Previsão simulada<strong>${canceled?'—':o.customer.timing==='scheduled'?formatSchedule(o.customer.schedule):o.mode==='pickup'?'25–35 min':'35–50 min'}</strong></div><div>Total do pedido<strong>${M(o.totals.total)}</strong></div></div>${canceled?`<div class="info-box" style="margin-top:20px"><strong>${E(o.status)}</strong><p>Converse com a equipe para esclarecer qualquer dúvida.</p></div>`:`<ol class="timeline">${sequence.map((s,i)=>`<li class="${i<=statusIndex?'complete':''} ${i===statusIndex?'current':''}"><span class="timeline-dot">${i<statusIndex?'✓':i+1}</span><span><strong>${s}</strong><small>${i<statusIndex?'Etapa concluída':i===statusIndex?'Etapa atual':'Aguardando'}</small></span></li>`).join('')}</ol>`}<a class="button secondary full" href="https://wa.me/5511999992026" target="_blank" rel="noopener">${I('whatsapp')} Falar com a Brasa Burger</a><div class="demo-controls"><p>Controle de demonstração: experimente a mudança de status.</p><label class="field"><span>Simular status do pedido</span><select id="demo-status">${B.statuses.map((s,i)=>`<option value="${E(s)}" ${s===o.status?'selected':''}>${E(sequence[i]||s)}</option>`).join('')}</select></label>${statusIndex<4?'<button class="button primary full" data-action="advance-order">Simular próxima etapa '+I('arrow')+'</button>':''}<button class="text-link" data-action="track">Consultar outro pedido</button></div></div>`;$('#tracking-dialog').setAttribute('aria-labelledby','tracking-title');show('#tracking-dialog')}
  function updateOrderStatus(status){state.tracking.status=status;if(!state.tracking.sample){const orders=B.get('brasa-orders',[]);const order=orders.find(o=>o.number===state.tracking.number);if(order){order.status=status;B.save('brasa-orders',orders)}}renderTracking()}
  document.addEventListener('click',event=>{const target=event.target.closest('button,a');if(!target)return;
    if(target.dataset.product){openProduct(target.dataset.product);return}
    if(target.dataset.category){state.category=target.dataset.category;renderMenu();return}
    if(target.dataset.remove!==undefined){state.cart.splice(Number(target.dataset.remove),1);persist();renderCart();return}
    if(target.dataset.quantity!==undefined){const i=Number(target.dataset.quantity);state.cart[i].qty+=Number(target.dataset.delta);if(state.cart[i].qty<=0)state.cart.splice(i,1);persist();renderCart();return}
    if(target.dataset.auth){captureCheckout();state.authMethod=target.dataset.auth;renderCheckout();return}
    if(target.dataset.step!==undefined){captureCheckout();state.step=Number(target.dataset.step);renderCheckout();return}
    const action=target.dataset.action;
    if(action==='close')target.closest('dialog')?.close();
    if(action==='theme')B.theme();
    if(action==='cart')openCart();
    if(action==='promo'){state.coupon='BRASA15';persist();B.toast('BRASA15 reservado! 15% OFF no seu carrinho.');if(navigator.clipboard)navigator.clipboard.writeText('BRASA15').catch(()=>{});$('#cardapio').scrollIntoView({behavior:'smooth'})}
    if(action==='product-minus'||action==='product-plus'){productDraft.qty=Math.max(1,Math.min(20,productDraft.qty+(action==='product-plus'?1:-1)));updateProductPrice()}
    if(action==='add-product')addProduct();
    if(action==='browse'){target.closest('dialog').close();$('#cardapio').scrollIntoView({behavior:'smooth'})}
    if(action==='reset-search'){state.query='';state.category='todos';$('#menu-search').value='';renderMenu()}
    if(action==='remove-coupon'){state.coupon='';persist();renderCart()}
    if(action==='checkout')startCheckout();
    if(action==='checkout-back'){captureCheckout();if(state.step){state.step--;renderCheckout()}else{$('#checkout-dialog').close();openCart()}}
    if(action==='demo-data'){captureCheckout();Object.assign(state.customer,{name:'Alex da Brasa',phone:'(11) 99999-2026',email:'alex@example.com',street:'Rua Exemplo',number:'123',complement:'',payment:'Pix'});renderCheckout()}
    if(action==='send-code'){captureCheckout();state.codeSent=true;renderCheckout();B.toast('Código demonstrativo: 123456. Nenhuma mensagem enviada.')}
    if(action==='track'){document.querySelectorAll('dialog[open]').forEach(d=>d.close());trackingLookup()}
    if(action==='track-current'){$('#checkout-dialog').close();renderTracking()}
    if(action==='sample-order')sampleOrder();
    if(action==='last-order'){state.tracking=B.get('brasa-orders',[]).find(o=>o.number===B.get('brasa-last-order',''));if(state.tracking)renderTracking();else B.toast('Pedido não encontrado neste navegador.')}
    if(action==='advance-order')updateOrderStatus(B.statuses[B.statuses.indexOf(state.tracking.status)+1]);
  });
  document.addEventListener('change',event=>{const t=event.target;if(t.name==='extra'){productDraft.extras=Array.from($('#product-dialog').querySelectorAll('[name="extra"]:checked')).map(e=>e.value);updateProductPrice()}if(t.name==='remove')productDraft.removed=Array.from($('#product-dialog').querySelectorAll('[name="remove"]:checked')).map(e=>e.value);if(t.id==='cart-neighborhood'){state.mode=t.value==='pickup'?'pickup':'delivery';state.neighborhood=t.value==='pickup'?'':t.value;persist();renderCart()}if(['mode','timing','payment'].includes(t.name)){captureCheckout();renderCheckout()}if(t.id==='demo-status')updateOrderStatus(t.value)});
  document.addEventListener('submit',event=>{const form=event.target;if(form.id==='coupon-form'){event.preventDefault();const code=$('#coupon-input').value.trim().toUpperCase();if(code==='BRASA15'){state.coupon=code;persist();renderCart()}else $('#coupon-feedback').textContent='Cupom não encontrado. Experimente BRASA15.'}if(form.id==='checkout-form'){event.preventDefault();captureCheckout();const error=validateStep();if(error){$('#checkout-error').textContent=error;return}if(state.step<3){state.step++;renderCheckout()}else confirmOrder()}if(form.id==='tracking-form'){event.preventDefault();const data=new FormData(form);const number=String(data.get('order')).replace('#','').trim();const phone=String(data.get('phone')).replace(/\D/g,'');const order=B.get('brasa-orders',[]).find(o=>o.number===number&&o.customer.phone.replace(/\D/g,'')===phone);if(order){state.tracking=order;renderTracking()}else $('#tracking-error').textContent='Não encontramos um pedido com esses dados neste navegador.'}});
  $('#menu-search').addEventListener('input',event=>{state.query=event.target.value;if(state.query)state.category='todos';renderMenu()});
  document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
  document.querySelectorAll('.nav-link').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.nav-link').forEach(n=>n.classList.toggle('active',n===a))}));
  window.addEventListener('storage',event=>{if(event.key==='brasa-orders'&&state.tracking&&!state.tracking.sample&&$('#tracking-dialog').open){const o=B.get('brasa-orders',[]).find(o=>o.number===state.tracking.number);if(o){state.tracking=o;renderTracking()}}});
  const logo=B.get('brasa-official-logo','');if(logo)document.querySelectorAll('.logo-slot').forEach(slot=>{slot.innerHTML=`<img src="${E(logo)}" alt="Logo oficial Brasa Burger Co." style="width:100%;height:100%;object-fit:contain">`;slot.style.border='none';slot.removeAttribute('title')});
  B.hydrate();B.updateTheme();storeStatus();setInterval(storeStatus,60000);renderMenu();updateCartBadges();
})();
