CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(190) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL,
 phone VARCHAR(20) NOT NULL DEFAULT '', password_hash VARCHAR(255) NULL,
 role ENUM('customer','kitchen','operator','manager','admin') NOT NULL DEFAULT 'customer',
 active BOOLEAN NOT NULL DEFAULT TRUE, verified_at DATETIME NULL,
 session_version INT NOT NULL DEFAULT 1, totp_secret TEXT NULL,
 totp_last_step BIGINT NOT NULL DEFAULT -1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS catalog_lock (id INT PRIMARY KEY, revision BIGINT NOT NULL DEFAULT 1) ENGINE=InnoDB;
INSERT IGNORE INTO catalog_lock(id,revision) VALUES(1,1);
CREATE TABLE IF NOT EXISTS catalog (
 kind VARCHAR(24) NOT NULL, id VARCHAR(64) NOT NULL, data JSON NOT NULL,
 revision INT NOT NULL DEFAULT 1, PRIMARY KEY(kind,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS challenges (
 id CHAR(48) PRIMARY KEY, user_id BIGINT UNSIGNED NULL, purpose VARCHAR(24) NOT NULL,
 verifier CHAR(64) NOT NULL, attempts INT NOT NULL DEFAULT 0,
 expires_at DATETIME NOT NULL, consumed_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id), INDEX(expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS rate_limits (
 bucket CHAR(64) PRIMARY KEY, hits INT UNSIGNED NOT NULL DEFAULT 1, expires_at DATETIME NOT NULL,
 INDEX(expires_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS addresses (
 id CHAR(32) PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, data JSON NOT NULL,
 FOREIGN KEY(user_id) REFERENCES users(id), INDEX(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS orders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, public_id CHAR(32) NOT NULL UNIQUE,
 user_id BIGINT UNSIGNED NOT NULL, request_key CHAR(64) NOT NULL,
 request_hash CHAR(64) NOT NULL, snapshot JSON NOT NULL,
 status VARCHAR(32) NOT NULL DEFAULT 'Recebido', payment_status VARCHAR(16) NOT NULL DEFAULT 'pending',
 total_cents INT UNSIGNED NOT NULL, revision INT NOT NULL DEFAULT 1,
 scheduled_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id), UNIQUE KEY(user_id,request_key), INDEX(status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS coupon_uses (
 coupon_id VARCHAR(64) NOT NULL, user_id BIGINT UNSIGNED NOT NULL, uses INT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY(coupon_id,user_id), FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS audit_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, actor_id BIGINT UNSIGNED NULL,
 action VARCHAR(64) NOT NULL, object_id VARCHAR(80) NOT NULL DEFAULT '', details JSON NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS outbox (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, payload TEXT NOT NULL,
 status ENUM('pending','sending','sent','failed') NOT NULL DEFAULT 'pending',
 attempts INT NOT NULL DEFAULT 0, available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 locked_at DATETIME NULL, sent_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(status,available_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS privacy_requests (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL,
 kind ENUM('access','correction','deletion') NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending',
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
