display_errors=Off
log_errors=On
expose_php=Off
date.timezone=UTC
upload_max_filesize=3M
post_max_size=4M
max_file_uploads=1
memory_limit=256M
max_execution_time=30
session.use_strict_mode=1
session.use_only_cookies=1
session.use_trans_sid=0
session.cookie_httponly=1
session.cookie_samesite=Lax
allow_url_include=Off
